---
title: "RWorksheet4b"
author: "Abdul Azim Bansara"
date: "2023-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.
```{r}
VectorA <- c(1,2,3,4,5)
matrixa <- matrix(VectorA, nrow=5, ncol=5)

Vector0 <- c(0)
matrix0 <- matrix(0, nrow=5,ncol=5)

for(i in length(VectorA)){
  matrix0[i,] <- abs(VectorA-VectorA[i])
}
print(matrix0)


```
\
2.
```{r}

for(i in 1:5){
  starneww <- rep("*",i)
  print(starneww)
}

```
\
3.
```{r}
yournum <- as.numeric(readline("Enter the starting number for fibonacci sequence: "))

a<-0
b<-1

cat("Fibonacci sequence starting from",yournum,"up to 500\n")
repeat{
  if(a>=yournum){
    cat(a," ")
  }
  if(a==377){
    break
  }
  numyours <- a+b
  a <- b
  b <- numyours
  
}
cat("\n")



```
\
4a.
```{r}
shoesize <- read.csv("datashoe")

shoesize


```
\
4b.
```{r}
malesub <- subset(shoesize, Gender == 'M')

femalesub <- subset(shoesize, Gender == 'F')

cat("Number of obsevation in male:",nrow(malesub),"\n")
cat("Number of observation in female",nrow(femalesub),"\n")




```
\
4c.
```{r}
gendermf <- table(shoesize$Gender)

barplot(gendermf,
        main = "The number of male and female",
        xlab = "Gender",
        ylab = "Count",
        col = c("red","pink"),
        legend.text =c("Male", "Female"))
```
\
5a.
```{r}
familyincome <- c(60,10,5,25)

pie(familyincome,labels = paste0(familyincome,"%"),
    main = "Dela Cruz Family Expenses", col = rainbow(length(familyincome)))

legend("topleft", legend = c("Food","Electricity", "Savings","Miscellaneous"),
       fill = rainbow(length(familyincome)))

```
\
6a.
```{r}
data(iris)

str(iris)

#there are 150 observation and 5 variables in iris dataset. there are numeric measurements in sepal.width, sepal.length, petal.width, and petal.length as well as the factor variable for the species

```

6b.
```{r}


```
\
6c.
```{r}





```

\
2.
```{r}
```
\
2.
```{r}
```

\
2.
```{r}
```

\
2.
```{r}
```

\
2.
```{r}
```


\
2.
```{r}
```


\
2.
```{r}
```


\
2.
```{r}
```




\
2.
```{r}
```



\
2.
```{r}
```




\
2.
```{r}
```




\
2.
```{r}
```
